name: Build Application

inputs:
  app-name:
    required: true
    type: string
         
runs:
  using: composite

  steps:
    - name: Build
      shell: bash
      run: echo ${{ inputs.app-name }} app built!
