name: Build Application

inputs:
  app_name:
    required: true
    type: string
         
runs:
  using: composite

  steps:
    - name: Build
      shell: bash
      run: echo ${{inputs.app_name}} app built!
