name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Build hello-world app
        uses: ./.github/actions/build-app
        with:
          app-name: 'hello-world'
          
  dev-deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment: Dev
    steps:
      - name: Build
        shell: bash
        run: echo Deploying ${{ inputs.app-name }} to dev         

  tst-deploy:
    runs-on: ubuntu-latest
    needs: [dev-deploy]
    environment: Tst
    steps:
      - name: Build
        shell: bash
        run: echo Deploying ${{ inputs.app-name }} to tst
        
  prd-deploy:
    runs-on: ubuntu-latest
    needs: [tst-deploy]
    environment: Prd
    steps:
      - name: Build
        shell: bash
        run: echo Deploying ${{ inputs.app-name }} to prd        
