name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Build hello-world app
        uses: ./.github/actions/build-app
        with:
          app-name: 'hello-world'
          
  DeployDev:
    runs-on: ubuntu-latest
    steps:
      - name: Build hello-2-world app
        uses: ./.github/actions/build-app
        with:
          app-name: 'hello-2-world'          
