name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    uses: octo-org/example-repo/.github/workflows/template/build/action.yml@main
    with:
      app-name: hello-world
    secrets:
      password: P455W0RD    


      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
